services:
  app:
    build: .
    image: face_analyze
    ports:
      - "8008:80"
    environment:
      PYTHONPYCACHEPREFIX: /tmp

  tests:
    build: .
    image: face_analyze
    command: pytest -s -v
    environment:
      PYTHONPYCACHEPREFIX: /tmp
    profiles: ["tests"]
